version: '3.8'

services:
  # talker:
  #   image: osrf/ros:humble
  #   command: ls

  # listener:
  #   image: osrf/ros:humble
  #   command: ls
  #   depends_on:
  #     - talker

  ros_base:
    image: osrf/ros:humble
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1

  robot_side:
    extends: ros_base
    image: osrf/gazebo:gzweb8


