<?xml version="1.0"?>
<robot name="diff_drive" xmlns:xacro="http://www.ros.org/wiki/xacro">


  <xacro:property name="sheep_plate_radius" value="0.2" />
  <xacro:property name="sheep_plate_thickness" value="0.05" />
  <xacro:property name="sheep_plate_height_from_ground" value="0.2" />
  <xacro:property name="wheel_radius" value="0.06" />
  <xacro:property name="wheel_thickness" value="0.02" />
  <!-- Base Link -->
  <link name="chassis">
    <visual>
      <origin xyz="0.0 0.0 ${sheep_plate_height_from_ground}" />
      <geometry>
        <cylinder radius="${sheep_plate_radius}" length="${sheep_plate_thickness}" />
      </geometry>
      <material name="blue" />
    </visual>
    <collision>
      <origin xyz="0.0 0.0 ${sheep_plate_height_from_ground}" />
      <geometry>
        <cylinder radius="${sheep_plate_radius}" length="${sheep_plate_thickness}" />
      </geometry>
    </collision>

    <inertial>
      <mass value="1.14395" />
      <inertia
        ixx="0.126164"
        ixy="0.0"
        ixz="0.0"
        iyy="0.416519"
        iyz="0.0"
        izz="0.481014" />
    </inertial>
  </link>


  <!-- left wheel Link -->
  <link name="left_wheel">
    <!-- <collision>
      <origin xyz="${wheel_thickness/2} ${-sheep_plate_height_from_ground} 0.0" rpy="0.0 1.5707 0.0" />
      <geometry>
        <sphere radius="${wheel_radius}" />
      </geometry>
    </collision> -->

    <visual>
      <!-- <origin xyz="${1 + wheel_thickness/2} ${-sheep_plate_height_from_ground} 0.0" -->
      <!-- rpy="0.0 1.5707 0.0" /> -->
      <!-- <origin xyz="${wheel_thickness/2} ${-sheep_plate_height_from_ground} 0.0" rpy="0.0 1.5707
      0.0" /> -->
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_thickness}" />
      </geometry>
      <material name="black" />
    </visual>

    <inertial>
      <mass value="2" />
      <inertia ixx="0.145833"
        ixy="0.0"
        ixz="0.0"
        iyy="0.145833"
        iyz="0.0"
        izz="0.125" />
    </inertial>
  </link>


  <!-- left wheel Link -->
  <link name="right_wheel">
    <!-- <collision>
      <origin xyz="${wheel_thickness/2} ${-sheep_plate_height_from_ground} 0.0" rpy="0.0 1.5707 0.0" />
      <geometry>
        <sphere radius="${wheel_radius}" />
      </geometry>
    </collision> -->

    <visual>
      <!-- <origin xyz="${wheel_thickness/2} ${-sheep_plate_height_from_ground} 0.0" rpy="0.0 1.5707
      0.0" /> -->
      <!-- <origin xyz="0.0 0.0 0.0" rpy="0.0 1.5707 0.0" /> -->
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_thickness}" />
      </geometry>
      <material name="black" />
    </visual>

    <inertial>
      <mass value="2" />
      <inertia ixx="0.145833"
        ixy="0.0"
        ixz="0.0"
        iyy="0.145833"
        iyz="0.0"
        izz="0.125" />
    </inertial>
  </link>

  <link name="caster">
    <!-- <collision>
      <geometry>
        <sphere radius="0.2" />
      </geometry>
    </collision> -->

    <visual>
      <geometry>
        <sphere radius="0.2" />
      </geometry>
      <material name="white" />
    </visual>

    <inertial>
      <origin xyz="-0.957138 -0 0.2" rpy="0 0 0" />
      <mass value="0.005" />
      <inertia
        ixx="0.1"
        ixy="0.0"
        ixz="0.0"
        iyy="0.1"
        iyz="0.0"
        izz="0.1" />
    </inertial>
  </link>


  <!-- joints -->

  <joint name="left_wheel_joint" type="continuous">
    <!-- <origin xyz="${sheep_plate_radius} 0.0 0" rpy="-1.5707 0 0" /> -->
    <parent link="chassis" />
    <!-- <origin xyz="0.0 0.0 0.0" rpy="0.0 1.5707 0.0" /> -->
    <origin xyz="0.0 ${sheep_plate_radius + wheel_thickness/2.0} ${sheep_plate_height_from_ground}"
      rpy="1.5707 0.0 0.0" />
    <child link="left_wheel" />
    <axis xyz="0 0 1" />
    <dynamics damping="0.2" />
  </joint>

  <joint name="right_wheel_joint" type="continuous">
    <!-- <origin xyz="${sheep_plate_radius} 0.0 0" rpy="-1.5707 0 0" /> -->
    <parent link="chassis" />
    <!-- <origin xyz="0.0 0.0 0.0" rpy="0.0 1.5707 0.0" /> -->
    <origin
      xyz="0.0 ${-(sheep_plate_radius + wheel_thickness/2.0)} ${sheep_plate_height_from_ground}"
      rpy="1.5707 0.0 0.0" />
    <child link="right_wheel" />
    <axis xyz="0 0 1" />
    <dynamics damping="0.2" />
  </joint>

  <joint name="caster_joint" type="fixed">
    <origin xyz="-0.957138 -0 0.2" rpy="0 0 0" />
    <parent link="chassis" />
    <child link="caster" />
  </joint>

  <!-- caster frontal wheel Link -->

  <ros2_control name="GazeboSystem" type="system">
    <hardware>
      <plugin>gazebo_ros2_control/GazeboSystem</plugin>
    </hardware>
    <joint name="left_wheel_joint">
      <command_interface name="velocity">
        <param name="min">-1</param>
        <param name="max">1</param>
      </command_interface>
      <state_interface name="position" />
      <state_interface name="velocity" />
    </joint>
    <joint name="right_wheel_joint">
      <command_interface name="velocity">
        <param name="min">-1</param>
        <param name="max">1</param>
      </command_interface>
      <state_interface name="position" />
      <state_interface name="velocity" />
    </joint>
  </ros2_control>

  <gazebo>
    <!-- Joint state publisher -->
    <plugin filename="libgazebo_ros2_control.so" name="gazebo_ros2_control">
      <parameters>$(find sheep-sim)/config/diff_drive_controller.yaml</parameters>
    </plugin>
  </gazebo>

</robot>