version: '3.9'
services:
  zed-camera:
    image: stereolabs/zed:3.4-ros-devel-l4t-r32.3.1
    container_name: zed_container
    privileged: true # Enable privileged mode for hardware access (e.g., for ZED camera)
    network_mode: host # Use the host network mode for better performance and ROS communication
    volumes:
      - /dev:/dev # Mount host's /dev folder for hardware access
    environment:
      - ROS_MASTER_URI=http://localhost:11311 # Set ROS master URI
      - ROS_IP=<your_host_ip> # Replace with your host machine's IP address
      - NVIDIA_VISIBLE_DEVICES=all
    # runtime: nvidia

  sim:
    image: sheep_sim:latest
    build:
      context: .
      dockerfile: docker/files/sheep-sim.Dockerfile

    command:
      [
        "/bin/bash",
        "-c",
        "cd /sheep && source install/setup.bash && make simulation"
      ]
    network_mode: host
    volumes:
      - .:/home/ros/sheep
  # listener:
  #   image: osrf/ros:humble-desktop
  #   command: ros2 run demo_nodes_cpp listener
  #   depends_on:
  #     - talker
